# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_description', models.TextField()),
                ('training_gil_description', models.TextField()),
                ('survey_gil_description', models.TextField()),
                ('training_selection_description', models.TextField()),
                ('survey_selection_description', models.TextField()),
                ('ending_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GilResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('Training GIL', 'Training GIL'), ('Survey GIL', 'Survey GIL'), ('Training Selection', 'Training Selection'), ('Survey Selection', 'Survey Selection')], max_length=100)),
                ('task_id', models.PositiveIntegerField(default=0)),
                ('clicks', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PilotModeResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.PositiveIntegerField()),
                ('cards_order', models.TextField(default=[])),
                ('correctness', models.CharField(default='-', max_length=20)),
                ('correct_cards', models.TextField(default=[])),
                ('start_time', models.PositiveIntegerField(default=0)),
                ('doing_task_time', models.CharField(default='-', max_length=20)),
                ('solving_task_time', models.CharField(default='-', max_length=20)),
                ('card_P_clicks', models.TextField(default='[]')),
                ('card_nP_clicks', models.TextField(default='[]')),
                ('card_Q_clicks', models.TextField(default='[]')),
                ('card_nQ_clicks', models.TextField(default='[]')),
                ('card_P_final', models.CharField(max_length=100, null=True)),
                ('card_nP_final', models.CharField(max_length=100, null=True)),
                ('card_Q_final', models.CharField(max_length=100, null=True)),
                ('card_nQ_final', models.CharField(max_length=100, null=True)),
                ('chosen_cards', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PilotModeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_description', models.TextField()),
                ('training_tasks', models.TextField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='SelectionResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.PositiveIntegerField()),
                ('cards_order', models.TextField(default=[])),
                ('correctness', models.CharField(default='-', max_length=20)),
                ('correct_cards', models.TextField(default=[])),
                ('start_time', models.PositiveIntegerField(default=0)),
                ('doing_task_time', models.CharField(default='-', max_length=20)),
                ('solving_task_time', models.CharField(default='-', max_length=20)),
                ('card_P_clicks', models.TextField(default='[]')),
                ('card_nP_clicks', models.TextField(default='[]')),
                ('card_Q_clicks', models.TextField(default='[]')),
                ('card_nQ_clicks', models.TextField(default='[]')),
                ('card_P_final', models.CharField(max_length=100, null=True)),
                ('card_nP_final', models.CharField(max_length=100, null=True)),
                ('card_Q_final', models.CharField(max_length=100, null=True)),
                ('card_nQ_final', models.CharField(max_length=100, null=True)),
                ('chosen_cards', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause', models.PositiveIntegerField()),
                ('training_gil_session_time', models.PositiveIntegerField(default=0)),
                ('survey_gil_session_time', models.PositiveIntegerField(default=0)),
                ('training_selection_session_time', models.PositiveIntegerField(default=0)),
                ('survey_selection_session_time', models.PositiveIntegerField(default=0)),
                ('training_tasks', models.TextField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('top_description', models.TextField()),
                ('bottom_description', models.TextField()),
                ('rule', models.TextField()),
                ('card_choice_description', models.TextField(default='')),
                ('card_P', models.TextField()),
                ('card_nP', models.TextField()),
                ('card_Q', models.TextField()),
                ('card_nQ', models.TextField()),
                ('correct_answers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.TextField()),
                ('done', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
