# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gilresults',
            name='task_id',
            field=models.PositiveIntegerField(),
        ),
    ]
